export const SANITIZED_SIKDAE_HISTORY_SAMPLE = {
  amount: {
    totalAmount: 813520,
    couponAmount: 0,
    policyAmount: 718500,
    myPointAmount: 10000,
    captainPayAmount: 85020,
    welfareAmount: 0,
  },
  histories: [
    {
      badgeName: "방문식사",
      useDate: 1673587201529.459,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 12500,
      payType: "AMOUNT",
      storeInfo: { storeName: "[위쿡딜리버리논현] 돈웍" },
    },
    {
      badgeName: "방문식사",
      useDate: 1673494286405.4504,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 8500,
      payType: "AMOUNT",
      storeInfo: { storeName: "본도시락(삼성점)" },
    },
    {
      badgeName: "방문식사",
      useDate: 1673410984095.6008,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 2200,
      payType: "AMOUNT",
      storeInfo: { storeName: "투썸플레이스(선릉로점)" },
    },
    {
      badgeName: "방문식사",
      useDate: 1673410905536.9587,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 6800,
      payType: "AMOUNT",
      storeInfo: { storeName: "투썸플레이스(선릉로점)" },
    },
    {
      badgeName: "방문식사",
      useDate: 1673324025388.76,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 18000,
      payType: "AMOUNT",
      storeInfo: { storeName: "잼라운지" },
    },
    {
      badgeName: "방문식사",
      useDate: 1673236976709.053,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 10000,
      payType: "AMOUNT",
      storeInfo: { storeName: "교동짬뽕(선릉)" },
    },
    {
      badgeName: "방문식사",
      useDate: 1672977746845.5068,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 9500,
      payType: "AMOUNT",
      storeInfo: { storeName: "육고탁(선릉점)" },
    },
    {
      badgeName: "방문식사",
      useDate: 1672889546761.0818,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 9000,
      payType: "AMOUNT",
      storeInfo: { storeName: "본도시락(삼성점)" },
    },
    {
      badgeName: "방문식사",
      useDate: 1672804831577.3447,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 16000,
      payType: "AMOUNT",
      storeInfo: { storeName: "카레공간(대치점)" },
    },
    {
      badgeName: "방문식사",
      useDate: 1672719299547.417,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 9000,
      payType: "AMOUNT",
      storeInfo: { storeName: "탄" },
    },
    {
      badgeName: "방문식사",
      useDate: 1672631793823.8013,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 7800,
      payType: "AMOUNT",
      storeInfo: { storeName: "본도시락(삼성점)" },
    },
    {
      badgeName: "방문식사",
      useDate: 1672375405366.5269,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 10000,
      payType: "AMOUNT",
      storeInfo: { storeName: "잼라운지" },
    },
    {
      badgeName: "방문식사",
      useDate: 1672286341758.1414,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 10000,
      payType: "AMOUNT",
      storeInfo: { storeName: "교동짬뽕(선릉)" },
    },
    {
      badgeName: "방문식사",
      useDate: 1672198439193.5627,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 9000,
      payType: "AMOUNT",
      storeInfo: { storeName: "본도시락(삼성점)" },
    },
    {
      badgeName: "방문식사",
      useDate: 1672027786319.147,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 9000,
      payType: "AMOUNT",
      storeInfo: { storeName: "원조양평해장국(선릉점)" },
    },
    {
      badgeName: "방문식사",
      useDate: 1671768099000.1255,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 11000,
      payType: "AMOUNT",
      storeInfo: { storeName: "육고탁(선릉점)" },
    },
    {
      badgeName: "방문식사",
      useDate: 1671681866363.8005,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 9200,
      payType: "AMOUNT",
      storeInfo: { storeName: "오한수우육면가(선릉점)" },
    },
    {
      badgeName: "방문식사",
      useDate: 1671507786190.8728,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 9000,
      payType: "AMOUNT",
      storeInfo: { storeName: "지구당(역삼점)" },
    },
    {
      badgeName: "방문식사",
      useDate: 1671422840201.6165,
      state: "CONFIRM",
      stateName: "결제 완료",
      price: 9000,
      payType: "AMOUNT",
      storeInfo: { storeName: "솔마루" },
    },
  ],
};
